### ISSUE TITLE
## Iniciativa del cliente de pedir listado de tiendas

### ISSUE THREAD

**Issue by nikodyulger** [nikodyulger/sistema-multiagente#12]

**Comment by nikodyulger** [comment]
Mira lo que han hecho uno de los grupos, ya tienen los esquemas, tan solo falta añadir las ip y puertos de las tiendas y clientes.

**Comment by nikodyulger** [comment]
El grupo en concreto es el 6. Modifica lo que creas conveniente y sube tu carpeta.

**Comment by NikoUcra** [comment]
[ClientePideTiendas.zip](https://github.com/nikodyulger/sistema-multiagente/files/5486565/ClientePideTiendas.zip)
