### ISSUE TITLE
## Inicio de comunicación

### ISSUE THREAD

**Issue by nikodyulger** [nikodyulger/sistema-multiagente#2]
- Petición GET por parte de tienda y cliente al monitor
- Respuesta del monitor (xml y xsd)
- Diagrama de secuencia

**Comment by pabloluqueromero** [comment]
Hemos creados los **2 diagramas de secuencia** para la creación de **tiendas y clientes** con sus correspondientes _schemas_ para definir la estructura de la respuesta en XML del monitor.

**Comment by nikodyulger** [comment]
Se debe añadir la ip y los puertos de comunicación del cliente y tienda en todos los esquemas y xml

**Comment by pabloluqueromero** [comment]
Vamos a  esperar a la clase del 4/11 para aclarar exactamente cómo se quiere hacer el head
